# Generated by Django 3.2.3 on 2021-07-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=200),
        ),
    ]
